samsung-dc-toolkit: init

diff --git a/.github/workflows/evergreen.yml b/.github/workflows/evergreen.yml
--- a/.github/workflows/evergreen.yml
+++ b/.github/workflows/evergreen.yml
@@ -78,7 +78,21 @@ jobs:
       - uses: DeterminateSystems/magic-nix-cache-action@main
       - name: Run update script for ${{ matrix.package }}
         id: run_update_script
-        run: "# Configure git \ngit config user.name \"github-actions\"\ngit config user.email \"github-actions@github.com\"\n\n# Run update script\nif nix-shell tasks/update.nix --argstr package \"${{ matrix.package }}\" --argstr commit true --argstr skip-prompt true; then\n  echo \"update.nix executed successfully\"\n  commits_count=$(git rev-list --all --count)\n  if [ \"$commits_count\" -ge 2 ]; then\n    echo \"pr_title=$(git show -s --format=%s HEAD)\" >> $GITHUB_OUTPUT\n  fi\nelse\n  echo \"update.nix execution failed\"\n  exit 1\nfi\n"
+        run: |
+          git config user.name "github-actions"
+          git config user.email "github-actions@github.com"
+
+          # Run update script
+          if nix-shell tasks/update.nix --argstr package "${{ matrix.package }}" --argstr commit true --argstr skip-prompt true; then
+            echo "update.nix executed successfully"
+            commits_count=$(git rev-list --all --count)
+            if [ "$commits_count" -ge 2 ]; then
+              echo "pr_title=$(git show -s --format=%s HEAD)" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "update.nix execution failed"
+            exit 1
+          fi
       - name: Create pull request
         uses: peter-evans/create-pull-request@v7
         if: steps.run_update_script.outputs.pr_title != ''
@@ -93,5 +107,5 @@ jobs:
           reviewers: "codgician"
       - name: Check build
         if: steps.run_update_script.outputs.pr_title != ''
-        run: |
+        run: |-
           nix build .#${{ matrix.package }}
